
title: Rich Pauloo
url: 'http://richpauloo.github.io'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Rich Pauloo
tagline: PhD Candidate | Data Scientist
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: richpauloo@gmail.com
phone: 415 275 4891
website: rpubs.com/richpauloo #do not add http://
linkedin: rpauloo
github: richpauloo
#twitter: '@webjeda'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
